---
apiVersion: iam.horizon.io/v1alpha2
kind: User
metadata:
  name: admin
  annotations:
    iam.horizon.io/uninitialized: 'true'
    helm.sh/resource-policy: keep
spec:
  email: admin@horizon.io
  password: {{ include "getOrDefaultPass" . | quote }}
status:
  state: Active
