apiVersion: v1
data:
  local_config.yaml: |
    server:
      http:
        hostname: localhost
        port: 8000
        static: 
          production:
            /public: server/public
            /assets: dist/assets
            /dist: dist
      redis:
        port: 6379
        host: redis.horizon-system.svc
      redisTimeout: 5000
      sessionTimeout: 7200000
    client:
      version:
        horizon: {{ .Chart.AppVersion }}
        kubernetes: {{ .Values.kube_version }}
        openpitrix: {{ .Chart.AppVersion }}
      enableKubeConfig: true
    defaultClusterName: {{ .Values.console.defaultClusterName }}
kind: ConfigMap
metdata:
  name: hz-console-config
