#

replicaCount: 1

image:

adminPassword: ''

config:
  create: true
  authentication:
    oauthOptions:
      clients:
        - name: horizon
          secret: horizon
          redirectURIs:
            - '*'
  jwtSecret: ''
  multicluster: {}
  monitoring: {}
  notification: {}

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  annotations: {}
  name: 'horizon'

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

kube_version: 'v0.0.1'

env: []

tolerations:
  - key: node-role.horizon.io/master
    effect: NoSchedule
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    tolerationSeconds: 60
  - effect: NoExecute
    key: node.horizon.io/unreachable
    operator: Exists
    tolerationSeconds: 60
affinity: {}

nodeSelector: {}

apiserver:
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 100Mi

  extraVolumeMounts: []

  extraVolumes: []

console:
  nodePort: 30880
  defaultClusterName: 'default'
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 100Mi

  extraVolumeMounts: []

  extraVolumes: []

controller:
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 30m
      memory: 50Mi
  extraVolumeMounts: []
  extraVolumes: []
